stages:
- name: Frontend install NPM packages
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        cd src/Frontend/ClientApp
        npm install
- name: Dotnet Build
  steps:
  - runScriptConfig:
      image: microsoft/dotnet
      shellScript: dotnet publish
timeout: 60
