FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 5003

FROM bibolorean/dotnet-nodejs AS build
WORKDIR /src
COPY ./NuGet.config ./NuGet.config
COPY ./src/Gateway/Gateway.csproj ./src/Gateway/Gateway.csproj
WORKDIR /src/src/Gateway/
RUN dotnet restore
WORKDIR /src
COPY ./src/Gateway ./src/Gateway

WORKDIR /src/src/Gateway/
RUN dotnet build "Gateway.csproj" -c Debug -o /app

FROM build AS publish
WORKDIR /src/src/Gateway/
RUN dotnet publish "Gateway.csproj" -c Debug -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Hypomos.Gateway.dll"]