FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 5003

FROM bibolorean/dotnet-nodejs AS build
WORKDIR /src
COPY ./src/Frontend/Frontend.csproj ./src/Frontend/Frontend.csproj
COPY ./src/ProxySupport/ProxySupport.csproj ./src/ProxySupport/ProxySupport.csproj
WORKDIR /src/src/Frontend/
RUN dotnet restore
COPY ./src/Frontend ./src/Frontend

WORKDIR /src/src/Frontend/
RUN dotnet restore "Frontend.csproj"
RUN dotnet build "Frontend.csproj" -c Debug -o /app

FROM build AS publish
WORKDIR /src/src/Frontend/
RUN dotnet publish "Frontend.csproj" -c Debug -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Hypomos.Frontend.dll"]