FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 5003

FROM bibolorean/dotnet-nodejs AS build
WORKDIR /src
COPY . .

WORKDIR /src/src/IdentityServer/
RUN dotnet restore "IdentityServer.csproj"
RUN dotnet build "IdentityServer.csproj" -c Debug -o /app

FROM build AS publish
WORKDIR /src/src/IdentityServer/
RUN dotnet publish "IdentityServer.csproj" -c Debug -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Hypomos.IdentityServer.dll"]