name: CI-simple
environment:
- LANG: C.UTF-8
- LANGUAGE: C.UTF-8
stages:
- name: clone
  steps:
  - sourceCodeConfig:
      branch: master
      branchCondition: only
      sourceCodeCredentialId: user-qpt9r:c-n8ssr-github-bwalti
      url: https://github.com/BWalti/hypomos.git
- name: Frontend install NPM packages
  steps:
  - runScriptConfig:
      image: node
      isShell: true
      shellScript: cd src/Frontend/ClientApp && npm install
- name: build
  steps:
  - runScriptConfig:
      image: microsoft/dotnet
      isShell: true
      shellScript: dotnet publish
